# Generated by Django 6.0.5 on 2026-06-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_author_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Book',
            new_name='books',
        ),
    ]
