# Generated by Django 6.0.5 on 2026-06-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Desciption',
            new_name='Description',
        ),
    ]
